FROM quay.io/sampandey001/secktor
RUN git clone https://github.com/ashenbro134/QUEEN-MINI-New/root/ashenbro134
WORKDIR /root/ashenbro134/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
